import React, { useState } from 'react';
import { SamplingParameters } from '../types/sampling';
import { ProviderType } from './EngineSettingsModal';
import { Code2, X, Copy, Check, Terminal, FileCode, Layers } from 'lucide-react';

interface CodeExportModalProps {
  isOpen: boolean;
  onClose: () => void;
  params: SamplingParameters;
  prompt: string;
  systemPrompt: string;
  ragContext: string;
  ragEnabled: boolean;
  modelName: string;
  provider: ProviderType;
}

export const CodeExportModal: React.FC<CodeExportModalProps> = ({
  isOpen,
  onClose,
  params,
  prompt,
  systemPrompt,
  ragContext,
  ragEnabled,
  modelName,
  provider,
}) => {
  const [activeTab, setActiveTab] = useState<'python' | 'langchain' | 'curl'>('python');
  const [copied, setCopied] = useState<boolean>(false);

  if (!isOpen) return null;

  const modelToUse = modelName || 'gpt-4o';

  // Construct Python Code Snippet
  const pythonSnippet = `# Production OpenAI Python SDK Setup
# Generated by "The Token Cosmos" Visual Sampling Engine

from openai import OpenAI

client = OpenAI()

response = client.chat.completions.create(
    model="${modelToUse}",
    messages=[
${systemPrompt.trim() ? `        {"role": "system", "content": "${systemPrompt.replace(/"/g, '\\"')}"},\n` : ''}${
      ragEnabled && ragContext.trim()
        ? `        {"role": "user", "content": "Retrieved Context: ${ragContext.replace(/"/g, '\\"')}\\n\\nQuestion: ${prompt.replace(/"/g, '\\"')}"}`
        : `        {"role": "user", "content": "${prompt.replace(/"/g, '\\"')}"}`
    }
    ],
    temperature=${params.temperature},
    top_p=${params.topP},
    frequency_penalty=${params.frequencyPenalty},
    presence_penalty=${params.presencePenalty},
${params.stopSequences.length > 0 ? `    stop=${JSON.stringify(params.stopSequences)},\n` : ''}${
      Object.keys(params.logitBiases).length > 0
        ? `    logit_bias=${JSON.stringify(params.logitBiases)},\n`
        : ''
    }    logprobs=True,
    top_logprobs=20,
)

print(response.choices[0].message.content)
`;

  // Construct LangChain TypeScript Snippet
  const langchainSnippet = `// Production LangChain TypeScript Setup
// Generated by "The Token Cosmos" Visual Sampling Engine

import { ChatOpenAI } from "@langchain/openai";
import { SystemMessage, HumanMessage } from "@langchain/core/messages";

const model = new ChatOpenAI({
  modelName: "${modelToUse}",
  temperature: ${params.temperature},
  topP: ${params.topP},
  frequencyPenalty: ${params.frequencyPenalty},
  presencePenalty: ${params.presencePenalty},
${params.stopSequences.length > 0 ? `  stopSequences: ${JSON.stringify(params.stopSequences)},\n` : ''}${
    Object.keys(params.logitBiases).length > 0
      ? `  logitBias: ${JSON.stringify(params.logitBiases)},\n`
      : ''
  }});

const messages = [
${systemPrompt.trim() ? `  new SystemMessage("${systemPrompt.replace(/"/g, '\\"')}"),\n` : ''}${
    ragEnabled && ragContext.trim()
      ? `  new HumanMessage("Context: ${ragContext.replace(/"/g, '\\"')}\\n\\nQuestion: ${prompt.replace(/"/g, '\\"')}")`
      : `  new HumanMessage("${prompt.replace(/"/g, '\\"')}")`
  }
];

const response = await model.invoke(messages);
console.log(response.content);
`;

  // Construct cURL Snippet
  const curlSnippet = `# cURL REST API Payload
# Generated by "The Token Cosmos" Visual Sampling Engine

curl https://api.openai.com/v1/chat/completions \\
  -H "Content-Type: application/json" \\
  -H "Authorization: Bearer $OPENAI_API_KEY" \\
  -d '{
    "model": "${modelToUse}",
    "messages": [
${systemPrompt.trim() ? `      {"role": "system", "content": "${systemPrompt.replace(/"/g, '\\"')}"},\n` : ''}${
    ragEnabled && ragContext.trim()
      ? `      {"role": "user", "content": "Context: ${ragContext.replace(/"/g, '\\"')}\\n\\nQuestion: ${prompt.replace(/"/g, '\\"')}"}`
      : `      {"role": "user", "content": "${prompt.replace(/"/g, '\\"')}"}`
  }
    ],
    "temperature": ${params.temperature},
    "top_p": ${params.topP},
    "frequency_penalty": ${params.frequencyPenalty},
    "presence_penalty": ${params.presencePenalty},
    "logprobs": true,
    "top_logprobs": 20
  }'
`;

  const getActiveCode = () => {
    switch (activeTab) {
      case 'python': return pythonSnippet;
      case 'langchain': return langchainSnippet;
      case 'curl': return curlSnippet;
    }
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(getActiveCode());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/80 backdrop-blur-md p-4 animate-in fade-in duration-200 select-text">
      <div className="w-full max-w-2xl rounded-2xl border border-cyan-500/30 bg-slate-950 p-6 shadow-2xl space-y-4">
        {/* Header */}
        <div className="flex items-center justify-between border-b border-slate-800 pb-3">
          <div className="flex items-center space-x-2.5">
            <div className="flex h-8 w-8 items-center justify-center rounded-xl bg-gradient-to-tr from-cyan-500 to-purple-600 p-0.5 shadow-neon-cyan">
              <div className="flex h-full w-full items-center justify-center rounded-[10px] bg-slate-950">
                <Code2 className="h-4 w-4 text-cyan-400" />
              </div>
            </div>
            <div>
              <h3 className="text-base font-bold text-slate-100">Export Production Sampling Code</h3>
              <p className="text-xs text-slate-400 font-mono">
                1-click runnable snippets matching your visualizer setup
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="rounded-lg p-1.5 text-slate-400 hover:bg-slate-800 hover:text-white"
          >
            <X className="h-4 w-4" />
          </button>
        </div>

        {/* Tab Selector & Copy Button */}
        <div className="flex items-center justify-between">
          <div className="flex rounded-lg bg-slate-900 p-1 border border-slate-800 font-mono text-xs">
            <button
              onClick={() => setActiveTab('python')}
              className={`flex items-center space-x-1.5 rounded-md px-3 py-1 font-bold transition-all ${
                activeTab === 'python'
                  ? 'bg-cyan-500 text-slate-950 shadow-md'
                  : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              <FileCode className="h-3.5 w-3.5" />
              <span>Python (OpenAI)</span>
            </button>
            <button
              onClick={() => setActiveTab('langchain')}
              className={`flex items-center space-x-1.5 rounded-md px-3 py-1 font-bold transition-all ${
                activeTab === 'langchain'
                  ? 'bg-purple-600 text-white shadow-md'
                  : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              <Layers className="h-3.5 w-3.5" />
              <span>TypeScript (LangChain)</span>
            </button>
            <button
              onClick={() => setActiveTab('curl')}
              className={`flex items-center space-x-1.5 rounded-md px-3 py-1 font-bold transition-all ${
                activeTab === 'curl'
                  ? 'bg-amber-500 text-slate-950 shadow-md'
                  : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              <Terminal className="h-3.5 w-3.5" />
              <span>cURL REST</span>
            </button>
          </div>

          <button
            onClick={handleCopy}
            className="flex items-center space-x-1.5 rounded-xl bg-gradient-to-r from-cyan-500 to-purple-600 px-3 py-1.5 text-xs font-bold text-white shadow-neon-cyan hover:opacity-90 transition-opacity"
          >
            {copied ? <Check className="h-3.5 w-3.5 text-emerald-300" /> : <Copy className="h-3.5 w-3.5" />}
            <span>{copied ? 'Copied to Clipboard!' : 'Copy Snippet'}</span>
          </button>
        </div>

        {/* Code Display Area */}
        <div className="relative rounded-xl bg-slate-900/90 border border-slate-800 p-4 max-h-[340px] overflow-y-auto font-mono text-xs leading-relaxed text-slate-200">
          <pre>{getActiveCode()}</pre>
        </div>
      </div>
    </div>
  );
};
