import React, { useState } from 'react';
import { SamplingParameters } from '../types/sampling';
import { ProviderType } from './EngineSettingsModal';
import { Code2, X, Copy, Check, Terminal, FileCode, Layers } from 'lucide-react';

interface CodeExportModalProps {
  isOpen: boolean;
  onClose: () => void;
  params: SamplingParameters;
  prompt: string;
  systemPrompt: string;
  ragContext: string;
  ragEnabled: boolean;
  modelName: string;
  provider: ProviderType;
  isReasoningModel?: boolean;
}

export const CodeExportModal: React.FC<CodeExportModalProps> = ({
  isOpen,
  onClose,
  params,
  prompt,
  systemPrompt,
  ragContext,
  ragEnabled,
  modelName,
  provider,
  isReasoningModel = false,
}) => {
  const [activeTab, setActiveTab] = useState<'openai' | 'anthropic' | 'gemini'>('openai');
  const [copied, setCopied] = useState<boolean>(false);

  if (!isOpen) return null;

  const modelToUse = modelName || 'gpt-4o';

  // Construct OpenAI Python Snippet
  const openaiSnippet = `# Production OpenAI Python SDK Setup
# Generated by "The Token Cosmos"

from openai import OpenAI

client = OpenAI()

response = client.chat.completions.create(
    model="${isReasoningModel ? 'o3-mini' : modelToUse}",
    messages=[
${systemPrompt.trim() ? `        {"role": "system", "content": "${systemPrompt.replace(/"/g, '\\"')}"},\n` : ''}${
      ragEnabled && ragContext.trim()
        ? `        {"role": "user", "content": "Retrieved Context: ${ragContext.replace(/"/g, '\\"')}\\n\\nQuestion: ${prompt.replace(/"/g, '\\"')}"}`
        : `        {"role": "user", "content": "${prompt.replace(/"/g, '\\"')}"}`
    }
    ],
${isReasoningModel ? `    max_completion_tokens=${params.maxThinkingTokens || 2048}, # Acts as thinking budget + output` : `    temperature=${params.temperature},
    top_p=${params.topP},
    frequency_penalty=${params.frequencyPenalty},
    presence_penalty=${params.presencePenalty},
${params.stopSequences.length > 0 ? `    stop=${JSON.stringify(params.stopSequences)},\n` : ''}${
      Object.keys(params.logitBiases).length > 0
        ? `    logit_bias=${JSON.stringify(params.logitBiases)},\n`
        : ''
    }    logprobs=True,
    top_logprobs=20,`}
)

print(response.choices[0].message.content)
`;

  // Construct Anthropic Snippet
  const anthropicSnippet = `# Production Anthropic Python SDK Setup
# Generated by "The Token Cosmos"

import anthropic

client = anthropic.Anthropic()

response = client.messages.create(
    model="${isReasoningModel ? 'claude-3-7-sonnet-20250219' : 'claude-3-5-sonnet-20241022'}",
    max_tokens=${isReasoningModel ? 20000 : 4096},
${systemPrompt.trim() ? `    system="${systemPrompt.replace(/"/g, '\\"')}",\n` : ''}${isReasoningModel ? `    thinking={
        "type": "enabled",
        "budget_tokens": ${params.maxThinkingTokens || 2048}
    },
` : `    temperature=${params.temperature},
`}    messages=[
${ragEnabled && ragContext.trim()
      ? `        {"role": "user", "content": "Context: ${ragContext.replace(/"/g, '\\"')}\\n\\nQuestion: ${prompt.replace(/"/g, '\\"')}"}`
      : `        {"role": "user", "content": "${prompt.replace(/"/g, '\\"')}"}`
}
    ]
)

print(response.content[0].text)
`;

  // Construct Gemini Snippet
  const geminiSnippet = `# Production Gemini Python SDK Setup
# Generated by "The Token Cosmos"

from google import genai
from google.genai import types

client = genai.Client()

${ragEnabled && ragContext.trim() ? `prompt_text = "Context: ${ragContext.replace(/"/g, '\\"')}\\n\\nQuestion: ${prompt.replace(/"/g, '\\"')}"` : `prompt_text = "${prompt.replace(/"/g, '\\"')}"`}

response = client.models.generate_content(
    model='${isReasoningModel ? 'gemini-2.5-pro' : 'gemini-2.5-flash'}',
    contents=prompt_text,
    config=types.GenerateContentConfig(
${systemPrompt.trim() ? `        system_instruction="${systemPrompt.replace(/"/g, '\\"')}",\n` : ''}${isReasoningModel ? `        thinking_config=types.ThinkingConfig(
            thinking_budget_tokens=${params.maxThinkingTokens || 2048}
        ),` : `        temperature=${params.temperature},
        top_p=${params.topP},
        top_k=${params.topK},`}
    )
)

print(response.text)
`;

  const getActiveCode = () => {
    switch (activeTab) {
      case 'openai': return openaiSnippet;
      case 'anthropic': return anthropicSnippet;
      case 'gemini': return geminiSnippet;
    }
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(getActiveCode());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="w-full h-full flex items-start justify-center animate-in fade-in duration-200 select-text">
      <div className="w-full max-w-3xl rounded-2xl border border-cyan-500/30 bg-[#15151a] p-6 shadow-2xl space-y-4">
        {/* Header */}
        <div className="flex items-center justify-between border-b border-slate-800 pb-3">
          <div className="flex items-center space-x-2.5">
            <div className="flex h-8 w-8 items-center justify-center rounded-xl bg-gradient-to-tr from-cyan-500 to-purple-600 p-0.5 shadow-neon-cyan">
              <div className="flex h-full w-full items-center justify-center rounded-[10px] bg-slate-950">
                <Code2 className="h-4 w-4 text-cyan-400" />
              </div>
            </div>
            <div>
              <h3 className="text-base font-bold text-slate-100">Export Production Sampling Code</h3>
              <p className="text-xs text-slate-400 font-mono">
                1-click runnable snippets matching your visualizer setup
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="rounded-lg p-1.5 text-slate-400 hover:bg-slate-800 hover:text-white"
          >
            <X className="h-4 w-4" />
          </button>
        </div>

        {/* Tab Selector & Copy Button */}
        <div className="flex items-center justify-between">
          <div className="flex rounded-lg bg-slate-900 p-1 border border-slate-800 font-mono text-xs">
            <button
              onClick={() => setActiveTab('openai')}
              className={`flex items-center space-x-1.5 rounded-md px-3 py-1 font-bold transition-all ${
                activeTab === 'openai'
                  ? 'bg-cyan-500 text-slate-950 shadow-md'
                  : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              <FileCode className="h-3.5 w-3.5" />
              <span>OpenAI API</span>
            </button>
            <button
              onClick={() => setActiveTab('anthropic')}
              className={`flex items-center space-x-1.5 rounded-md px-3 py-1 font-bold transition-all ${
                activeTab === 'anthropic'
                  ? 'bg-purple-600 text-white shadow-md'
                  : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              <Layers className="h-3.5 w-3.5" />
              <span>Anthropic API</span>
            </button>
            <button
              onClick={() => setActiveTab('gemini')}
              className={`flex items-center space-x-1.5 rounded-md px-3 py-1 font-bold transition-all ${
                activeTab === 'gemini'
                  ? 'bg-amber-500 text-slate-950 shadow-md'
                  : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              <Terminal className="h-3.5 w-3.5" />
              <span>Gemini API</span>
            </button>
          </div>

          <button
            onClick={handleCopy}
            className="flex items-center space-x-1.5 rounded-xl bg-gradient-to-r from-cyan-500 to-purple-600 px-3 py-1.5 text-xs font-bold text-white shadow-neon-cyan hover:opacity-90 transition-opacity"
          >
            {copied ? <Check className="h-3.5 w-3.5 text-emerald-300" /> : <Copy className="h-3.5 w-3.5" />}
            <span>{copied ? 'Copied to Clipboard!' : 'Copy Snippet'}</span>
          </button>
        </div>

        {/* Code Display Area */}
        <div className="relative rounded-xl bg-slate-900/90 border border-slate-800 p-4 max-h-[340px] overflow-y-auto font-mono text-xs leading-relaxed text-slate-200">
          <pre>{getActiveCode()}</pre>
        </div>
      </div>
    </div>
  );
};
