import { PresetScenario, RawTokenCandidate } from '../types/sampling';

export const PRESET_SCENARIOS: PresetScenario[] = [
  {
    id: 'factual-roboticist',
    name: 'Legal & Contract Extraction',
    subtitle: 'Temp: 0.05 • Min-P: 0.05 • RAG: ON',
    description: 'Ultra-deterministic factual extraction with strict context anchoring. Eliminates creative guesswork for legal clauses.',
    icon: 'FileText',
    params: {
      temperature: 0.05,
      topK: 5,
      topP: 1.0,
      minP: 0.05,
      frequencyPenalty: 0.0,
      presencePenalty: 0.0,
      stopSequences: [],
      logitBiases: {},
    },
    ragEnabled: true,
    prompt: 'What is the governing law and liability limit specified in the agreement?',
    ragContext: 'This Agreement shall be governed by the laws of Delaware. Aggregate liability under Section 8 shall not exceed $1,000,000.',
  },
  {
    id: 'strict-guardrail',
    name: 'Code & SQL Generator',
    subtitle: 'Temp: 0.01 • Schema: ON • Stop: \\n\\n',
    description: 'Zero-temperature greedy mode with stop sequences for structured JSON, SQL queries, and code syntax generation.',
    icon: 'Code',
    params: {
      temperature: 0.01,
      topK: 50,
      topP: 1.0,
      minP: 0.1,
      frequencyPenalty: 0.2,
      presencePenalty: 0.0,
      stopSequences: ['\n\n', '```'],
      logitBiases: {
        'Delve': -100,
        'delve': -100,
      },
    },
    ragEnabled: false,
    prompt: 'Write an optimized PostgreSQL query to count active users by region.',
    ragContext: '',
  },
  {
    id: 'balanced-navigator',
    name: 'Medical Record Summarizer',
    subtitle: 'Temp: 0.10 • Top-K: 10 • RAG: ON',
    description: 'High precision medical QA mode. Tethered strictly to clinical notes to prevent hallucinated medical advice.',
    icon: 'Clipboard',
    params: {
      temperature: 0.10,
      topK: 10,
      topP: 0.9,
      minP: 0.02,
      frequencyPenalty: 0.1,
      presencePenalty: 0.1,
      stopSequences: [],
      logitBiases: {},
    },
    ragEnabled: true,
    prompt: 'What was the patient\'s blood pressure and prescribed dosage?',
    ragContext: 'Patient presents with blood pressure 120/80 mmHg. Prescribed Amoxicillin 500mg orally twice daily for 7 days.',
  },
  {
    id: 'wild-storyteller',
    name: 'Creative & Game Dialogue',
    subtitle: 'Temp: 1.30 • Top-P: 0.95 • Freq Pen: 0.8',
    description: 'High entropy nucleus sampling for NPC dialogue, creative world-building, and unconstrained brainstorming.',
    icon: 'MessageSquare',
    params: {
      temperature: 1.30,
      topK: 50,
      topP: 0.95,
      minP: 0.01,
      frequencyPenalty: 0.8,
      presencePenalty: 0.5,
      stopSequences: [],
      logitBiases: {},
    },
    ragEnabled: false,
    prompt: 'Deep in the glowing cybernetic forest, the ancient automaton discovered...',
    ragContext: '',
  },
];

/**
 * High quality candidate logits for local instant demonstration without requiring model download.
 */
export const SAMPLE_RAW_LOGITS_MAP: Record<string, { baseline: RawTokenCandidate[]; rag: RawTokenCandidate[] }> = {
  'capital-france': {
    baseline: [
      { token_id: 101, token_str: ' Paris', raw_logit: 12.5, is_rag_grounded: false },
      { token_id: 102, token_str: ' France', raw_logit: 8.2, is_rag_grounded: false },
      { token_id: 103, token_str: ' London', raw_logit: 6.4, is_rag_grounded: false },
      { token_id: 104, token_str: ' Lyon', raw_logit: 5.8, is_rag_grounded: false },
      { token_id: 105, token_str: ' Marseille', raw_logit: 5.1, is_rag_grounded: false },
      { token_id: 106, token_str: ' Berlin', raw_logit: 4.2, is_rag_grounded: false },
      { token_id: 107, token_str: ' Rome', raw_logit: 3.9, is_rag_grounded: false },
      { token_id: 108, token_str: ' Madrid', raw_logit: 3.5, is_rag_grounded: false },
      { token_id: 109, token_str: ' Tokyo', raw_logit: 2.8, is_rag_grounded: false },
      { token_id: 110, token_str: ' Washington', raw_logit: 2.1, is_rag_grounded: false },
      { token_id: 111, token_str: ' beautiful', raw_logit: 1.8, is_rag_grounded: false },
      { token_id: 112, token_str: ' known', raw_logit: 1.5, is_rag_grounded: false },
      { token_id: 113, token_str: ' famous', raw_logit: 1.2, is_rag_grounded: false },
      { token_id: 114, token_str: ' located', raw_logit: 0.9, is_rag_grounded: false },
      { token_id: 115, token_str: ' home', raw_logit: 0.7, is_rag_grounded: false },
      { token_id: 116, token_str: ' the', raw_logit: 0.5, is_rag_grounded: false },
      { token_id: 117, token_str: ' a', raw_logit: 0.3, is_rag_grounded: false },
      { token_id: 118, token_str: ' historic', raw_logit: 0.1, is_rag_grounded: false },
      { token_id: 119, token_str: ' vibrant', raw_logit: -0.2, is_rag_grounded: false },
      { token_id: 120, token_str: ' bustling', raw_logit: -0.5, is_rag_grounded: false },
      ...Array.from({ length: 30 }, (_, i) => ({
        token_id: 200 + i,
        token_str: ` candidate_${i + 1}`,
        raw_logit: -1.0 - i * 0.3,
        is_rag_grounded: false,
      })),
    ],
    rag: [
      { token_id: 101, token_str: ' Paris', raw_logit: 18.9, is_rag_grounded: true },
      { token_id: 121, token_str: ' Eiffel', raw_logit: 14.2, is_rag_grounded: true },
      { token_id: 122, token_str: ' Tower', raw_logit: 12.8, is_rag_grounded: true },
      { token_id: 102, token_str: ' France', raw_logit: 7.1, is_rag_grounded: true },
      { token_id: 123, token_str: ' 1889', raw_logit: 6.5, is_rag_grounded: true },
      { token_id: 103, token_str: ' London', raw_logit: 1.2, is_rag_grounded: false },
      { token_id: 104, token_str: ' Lyon', raw_logit: 1.0, is_rag_grounded: false },
      { token_id: 105, token_str: ' Marseille', raw_logit: 0.8, is_rag_grounded: false },
      { token_id: 106, token_str: ' Berlin', raw_logit: 0.4, is_rag_grounded: false },
      { token_id: 107, token_str: ' Rome', raw_logit: 0.2, is_rag_grounded: false },
      ...Array.from({ length: 40 }, (_, i) => ({
        token_id: 300 + i,
        token_str: ` fringe_${i + 1}`,
        raw_logit: -1.5 - i * 0.2,
        is_rag_grounded: false,
      })),
    ],
  },
  'cybernetic-forest': {
    baseline: [
      { token_id: 501, token_str: ' a', raw_logit: 9.8, is_rag_grounded: false },
      { token_id: 502, token_str: ' an', raw_logit: 9.2, is_rag_grounded: false },
      { token_id: 503, token_str: ' crystalline', raw_logit: 8.7, is_rag_grounded: false },
      { token_id: 504, token_str: ' forgotten', raw_logit: 8.1, is_rag_grounded: false },
      { token_id: 505, token_str: ' relic', raw_logit: 7.5, is_rag_grounded: false },
      { token_id: 506, token_str: ' pulse', raw_logit: 7.2, is_rag_grounded: false },
      { token_id: 507, token_str: ' glowing', raw_logit: 6.8, is_rag_grounded: false },
      { token_id: 508, token_str: ' hidden', raw_logit: 6.4, is_rag_grounded: false },
      { token_id: 509, token_str: ' secret', raw_logit: 5.9, is_rag_grounded: false },
      { token_id: 510, token_str: ' sanctuary', raw_logit: 5.4, is_rag_grounded: false },
      { token_id: 511, token_str: ' signal', raw_logit: 5.0, is_rag_grounded: false },
      { token_id: 512, token_str: ' memory', raw_logit: 4.6, is_rag_grounded: false },
      { token_id: 513, token_str: ' core', raw_logit: 4.2, is_rag_grounded: false },
      ...Array.from({ length: 37 }, (_, i) => ({
        token_id: 600 + i,
        token_str: ` Echo_${i + 1}`,
        raw_logit: 3.5 - i * 0.2,
        is_rag_grounded: false,
      })),
    ],
    rag: [],
  },
};
