// src/lib/github.ts

export interface DoraMetrics {
  deploymentFrequency: string;
  leadTimeForChanges: string;
  changeFailureRate: string;
  timeToRestoreService: string;
}

export interface SpaceMetrics {
  satisfaction: number;
  activity: number;
  efficiency: number;
}

export interface AdrRecord {
  id: string;
  title: string;
  status: 'Approved' | 'Proposed' | 'Draft';
  date: string;
}

export interface DeploymentEvent {
  id: string;
  sha: string;
  status: 'success' | 'failure';
  timestamp: string;
  duration: string;
}

export interface TrackerData {
  dora: DoraMetrics;
  space: SpaceMetrics;
  deployments: DeploymentEvent[];
  adrs: AdrRecord[];
  lastUpdated: string;
}

/**
 * Ephemeral Static Architecture:
 * The data layer no longer uses a client-side PAT or hits the live GitHub API.
 * It strictly fetches a pre-compiled, static metrics.json file generated by our CI pipeline.
 */
export const fetchTrackerData = async (): Promise<TrackerData> => {
  // Using import.meta.env.BASE_URL ensures the fetch works when deployed to /tracker/
  const url = `${import.meta.env.BASE_URL}metrics.json`;
  
  try {
    const response = await fetch(url);
    if (!response.ok) {
      throw new Error(`Failed to fetch metrics: ${response.statusText}`);
    }
    return await response.json();
  } catch (error) {
    console.error("Tracker Data Fetch Error:", error);
    throw error;
  }
};
